### PR TITLE
Display Errors in templates

### PR DESCRIPTION
**Pull request by man4red**
The Error Template doesn't show common errors

### CODE REVIEW

**Comment by dollyaswin** [comment]
Hi @man4red,

Thanks for your `PR`, I have merge it to master branch. But for next `PR` please create `PR` for just `development` branch, it will be merge to `master` when I create new release.

Regards
Dolly

**Comment by man4red** [comment]
Sure! Thx

**Comment by man4red** [comment]
btw is it necessary to use "zfcampus/zf-deploy" ?
It seems that zf-deploy is abadoned for some reason

```
Package herrera-io/json is abandoned, you should avoid using it. Use kherge/json instead.
Package kherge/version is abandoned, you should avoid using it. No replacement was suggested.
Package herrera-io/phar-update is abandoned, you should avoid using it. No replacement was suggested.
```

**Comment by dollyaswin** [comment]
Hi @man4red,

I never used `zfcampus/zf-deploy`. I have see that, and it used to build .zpk file right? Is there any benefit from this tool. Please let me know.

Thanks

**Comment by man4red** [comment]
@dollyaswin 
I'm not sure if zf-deploy is used in your project.

Could you provide any login process example for you project?

Can't understand how to build it properly
If I signup second time - there is SQL exception on duplicate entry of course
Not sure if I'm using it right

Thanks!

**Comment by dollyaswin** [comment]
Hi @man4red,

If you got `duplicate entry` error message, it mean you signup using the same `email address`. I set `email address` as `UNIQUE`, so cannot insert same `email address`

Regards

**Comment by man4red** [comment]
@dollyaswin 

Yep! Totally )

I mean - could you please provide a login example (extend class or smth?)
I can't understand how to build it properly

Thanks

**Pull request merged**
